### ISSUE TITLE
[Major] Cannot undo my choices selected for Dietary Restriction 

### ISSUE THREAD

**Issue by joonbot1999** [info442-aut21/f-team#81]
When I select options and deselect some options for different search results, it doesn't update nor does it have any indications of what's happening.
environment: Chrome Version 96.0.4664.45, Omen 15
steps to reproduce: select all options initially, click enter, deselect all options, then click again
expected result: no result found/different result/some form of indicator
actual result: no dynamic change nor indicator or what has changed

**Comment by cherimarie** [comment]
I think this is a major issue, not minor.

**Comment by sershon** [comment]
Thank you for reporting! We may have forgot to add an event for what happens when you uncheck, or click the box again. We are going to change it so that upon unchecking it, it'll change the selected value back to empty.

**Comment by cherimarie** [comment]
Reminder: This needs to be upgraded to major level. The lack of feedback to users combined with crashes on page refresh make it nearly impossible to workaround. 

I believe this issue is effectively the same as https://github.com/info442-aut21/f-team/issues/61. One can be marked "duplicate" and closed, though both reporters will get credit.

**Comment by sershon** [comment]
Closed with latest pull request.
